return {}
-- return {
--   "HakonHarnes/img-clip.nvim",
--   event = "BufRead */*.md",
--   opts = {
--     -- add options here
--     -- or leave it empty to use the default settings
--     default = {
--       dir_path = "./z_attachments",
--       relative_to_current_file = true,
--       process_cmd = "convert - -set gamma 0.4545 -",
--     },
--   },
--   keys = {
--     -- suggested keymap
--     { "<leader>mp", "<cmd>PasteImage<cr>", desc = "Paste image from system clipboard" },
--   },
-- }
